[package]
name = "tpt-app-media-asset-intelligence-queue"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tpt-app-media-asset-intelligence-model = { path = "../tpt-app-media-asset-intelligence-model" }
tpt-app-media-asset-intelligence-ingest = { path = "../tpt-app-media-asset-intelligence-ingest" }
tpt-app-media-asset-intelligence-health = { path = "../tpt-app-media-asset-intelligence-health" }
tpt-app-media-asset-intelligence-persistence = { path = "../tpt-app-media-asset-intelligence-persistence" }
chrono.workspace = true
thiserror.workspace = true
uuid.workspace = true