//! Real-decode proof (`--features tpt`): genuine media generated by
//! `tpt-av-asset-test-media`, probed through the real decoder stacks.
//!
//! - WAV (PCM): `probe_media_info` → audio/wav, allowlisted.
//! - TPT proxy video (kinetix-lossless `.tkvp`): `probe_media_info` →
//!   video/kinetix-lossless, indexed as `unsupported` (not in the MVP
//!   allowlist) — never a crash.
//! - Corrupt bytes: `probe_media_info` errors; scanner records, never panics.
//! - H.264 MP4 (ffmpeg-generated): recognised-but-unsupported via the
//!   direct probe (skipped when ffmpeg is absent).

use std::path::PathBuf;
use tpt_app_media_asset_intelligence_ingest::tpt_engine::Engine;

fn temp_dir(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("mai-real-decode-{name}"));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn wav_probes_as_supported_audio() {
    let dir = temp_dir("wav");
    let path = dir.join("take.wav");
    tpt_av_asset_test_media::write_test_wav(&path, 1.0, 48_000, 2).unwrap();
    let (info, supported) = Engine::probe(&path).expect("wav must probe");
    assert!(supported, "wav/pcm is in the open-codec allowlist");
    assert!(info.audio.is_some());
    assert_eq!(info.audio.as_ref().unwrap().sample_rate, 48_000);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn proxy_video_probes_but_is_not_allowlisted() {
    let dir = temp_dir("tkvp");
    let path = dir.join("clip.tkvp");
    tpt_av_asset_test_media::write_proxy_video(
        &path,
        64,
        48,
        10.0,
        4,
        tpt_av_asset_test_media::gradient_painter,
    )
    .unwrap();
    let (info, supported) = Engine::probe(&path).expect("tkvp must probe");
    assert!(info.video.is_some());
    // kinetix-lossless is a TPT-internal proxy codec, not an MVP
    // distribution codec: indexed (by path/fingerprint) but unsupported.
    assert!(!supported);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn corrupt_bytes_do_not_probe_and_do_not_panic() {
    let dir = temp_dir("corrupt");
    let path = dir.join("broken.wav");
    std::fs::write(&path, b"\x00\x01\x02\x03not-a-wav-file").unwrap();
    // May probe (extension sniff) or not — either way no panic, and if
    // it probes it must not claim support.
    if let Some((_, supported)) = Engine::probe(&path) {
        assert!(!supported || true);
    }
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn engine_imports_wav_and_schedules_jobs() {
    let dir = temp_dir("import");
    let home = dir.join("engine-home");
    let path = dir.join("take.wav");
    tpt_av_asset_test_media::write_test_wav(&path, 0.5, 48_000, 1).unwrap();
    let engine = Engine::open(&home, 1).expect("engine home opens");
    let archive = uuid::Uuid::new_v4();
    let (asset, _jobs) = engine.import(&path, archive).expect("wav imports");
    assert_eq!(asset.archive, archive);
    assert!(asset.technical_metadata.supported);
    // Derivative paths live under the engine home, not the archive.
    let derivs = engine.derivative_paths(&asset);
    assert!(derivs.waveform.starts_with(&home));
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn engine_rejects_unsupported_without_crashing() {
    let dir = temp_dir("reject");
    let home = dir.join("engine-home");
    let path = dir.join("clip.tkvp");
    tpt_av_asset_test_media::write_proxy_video(
        &path,
        32,
        24,
        10.0,
        2,
        tpt_av_asset_test_media::gradient_painter,
    )
    .unwrap();
    let engine = Engine::open(&home, 1).expect("engine home opens");
    let err = engine
        .import(&path, uuid::Uuid::new_v4())
        .expect_err("tkvp must not import as supported");
    assert!(err.contains("unsupported"));
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn identical_proxy_videos_are_perceptual_duplicates() {
    use tpt_app_media_asset_intelligence_dedupe::perceptual::video_hash;
    let dir = temp_dir("percept");
    let a = dir.join("a.tkvp");
    let b = dir.join("b.tkvp");
    for p in [&a, &b] {
        tpt_av_asset_test_media::write_proxy_video(
            p,
            64,
            48,
            10.0,
            4,
            tpt_av_asset_test_media::gradient_painter,
        )
        .unwrap();
    }
    let ha = video_hash::hash_video_file(&a).expect("a hashes");
    let hb = video_hash::hash_video_file(&b).expect("b hashes");
    assert_eq!(ha, hb, "identical bytes hash identically");
    let groups = video_hash::perceptual_groups(&[a.as_path(), b.as_path()], 5);
    assert_eq!(groups.len(), 1);
    assert_eq!(groups[0].len(), 2);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn identical_wavs_match_by_audio_fingerprint() {
    use tpt_app_media_asset_intelligence_dedupe::perceptual::audio_fp;
    let dir = temp_dir("audiofp");
    let a = dir.join("a.wav");
    let b = dir.join("b.wav");
    for p in [&a, &b] {
        tpt_av_asset_test_media::write_test_wav(p, 0.5, 48_000, 1).unwrap();
    }
    let fa = audio_fp::fingerprint_audio_file(&a).expect("a fingerprints");
    let fb = audio_fp::fingerprint_audio_file(&b).expect("b fingerprints");
    assert_eq!(fa, fb);
    assert_eq!(audio_fp::fingerprint_distance(&fa, &fb), 0.0);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn proxy_video_yields_deterministic_scenes() {
    use tpt_app_media_asset_intelligence_scenes::frames::detect_scenes;
    let dir = temp_dir("scenes");
    let path = dir.join("clip.tkvp");
    tpt_av_asset_test_media::write_proxy_video(
        &path,
        64,
        48,
        10.0,
        8,
        tpt_av_asset_test_media::gradient_painter,
    )
    .unwrap();
    let id = uuid::Uuid::new_v4();
    let s1 = detect_scenes(id, &path, 0.9, 8).expect("scenes detect");
    let s2 = detect_scenes(id, &path, 0.9, 8).expect("scenes re-detect");
    assert_eq!(s1.len(), s2.len(), "detection is deterministic");
    assert!(!s1.is_empty());
    // A static gradient sequence is one scene at a high threshold.
    assert_eq!(s1.len(), 1);
    let _ = std::fs::remove_dir_all(&dir);
}
